# GET all locations
GET http://localhost:3000/api/wordpairs

###

GET http://localhost:3000/api/wordpairs/3

###


PUT http://localhost:3000/api/wordpairs/3
Content-Type: application/json

{
  "english": "caca",
  "finnish": "doodoo"
}
###

DELETE http://localhost:3000/api/wordpairs/2